name: YES Program
pygments: true
markdown: rdiscount
baseurl: /YES
permalink: :categories/:title
rdiscount extensions: [smart]


links:
- name: github
  href: http://www.github.com/shaoweiD/YES
  class: fa-github
  target: _blank
  level: 1
- name: ISU-Mechanical Engineering
  href: http://www.me.iastate.edu/
  class: fa-home
  target: _blank
  level: 1
- name: contact
  href: '#'
  class: fa-envelope
  target: _self
  level: 1
  type: dropdown
- name: The Claussen Group
  href: http://shaoweid.github.io/group.github.io/
  class: ''
  target: _blank
  level: 2
  parent: contact





